services:
  - type: web
    name: fair-lawn-energy-calculator
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/test
    healthCheckTimeout: 60
    autoDeploy: true
    envVars:
      - key: API_KEY
        sync: false
      - key: API_BASE_URL
        value: https://api.rewiringamerica.org
      - key: PORT
        value: 3000 